/*
 * Copyright (C) 2015 ilknur
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package terp.core.gui;

import terp.core.model.CompanyTableModel;
import terp.plugin.Application;
import terp.plugin.data.ICompany;
import terp.plugin.data.IDatabase;

/**
 *
 * @author ilknur
 */
public class CompanyForm extends javax.swing.JInternalFrame {

    private Application app = null;
    
    /**
     * Creates new form CompanyForm
     */
    public CompanyForm() {
        initComponents();        
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompany = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Company");
        setToolTipText("");
        setName("Companies"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblCompany.setAutoCreateColumnsFromModel(false);
        tblCompany.setModel(new CompanyTableModel());
        tblCompany.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblCompany);
        tblCompany.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formİnternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameClosing
        terp.plugin.Application app = terp.plugin.Application.getInstance();
        app.getMenuManager().setButtonEnabled("Administration", "Company", true);
    }//GEN-LAST:event_formİnternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCompany;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        
       this.app = Application.getInstance();
       IDatabase db = app.getDatabase();
       ICompany cmpDb = db.createCompanyDao();
       
       CompanyTableModel companyTableModel = 
               new CompanyTableModel(cmpDb.getColumns());
       
       this.tblCompany.setModel(companyTableModel);
       
       companyTableModel.updateData(cmpDb.findAll());
       
    }
}
