/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package terp.gui;

import java.awt.Component;
import javax.swing.JPanel;
import terp.plugin.IDesktopManager;
import terp.plugin.IMenuManager;

/**
 *
 * @author ilknur
 */
public class MainFrame extends javax.swing.JFrame implements IMenuManager,
        IDesktopManager {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        ribbon = new javax.swing.JTabbedPane();
        fileTab = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnSetupOptions = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        txtSearch.setText("Search");
        txtSearch.setToolTipText("");
        txtSearch.setMaximumSize(new java.awt.Dimension(180, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(180, 30));

        btnRun.setText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-ERP");

        jPanel1.setPreferredSize(new java.awt.Dimension(628, 105));

        ribbon.setPreferredSize(new java.awt.Dimension(400, 100));

        fileTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        fileTab.setPreferredSize(new java.awt.Dimension(138, 55));
        fileTab.setLayout(new javax.swing.BoxLayout(fileTab, javax.swing.BoxLayout.LINE_AXIS));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terp/resources/images/carpi32x32.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setToolTipText("Exit to system");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(70, 60));
        btnExit.setMinimumSize(new java.awt.Dimension(69, 59));
        btnExit.setName(""); // NOI18N
        btnExit.setPreferredSize(new java.awt.Dimension(70, 60));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        fileTab.add(btnExit);

        btnSetupOptions.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSetupOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/terp/resources/images/setup32x32.png"))); // NOI18N
        btnSetupOptions.setText("Options");
        btnSetupOptions.setToolTipText("Setup opions");
        btnSetupOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetupOptions.setMaximumSize(new java.awt.Dimension(70, 60));
        btnSetupOptions.setPreferredSize(new java.awt.Dimension(70, 60));
        btnSetupOptions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileTab.add(btnSetupOptions);

        ribbon.addTab("File", null, fileTab, "");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ribbon, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ribbon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        desktop.setAlignmentX(0.0F);
        desktop.setAlignmentY(0.0F);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO : run program
        
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnSetupOptions;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JPanel fileTab;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane ribbon;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setButtonEnabled(String tabName, String btnName, boolean enabled) {
        //find tab
        int index = ribbon.indexOfTab(tabName);
        
        //if tab isfound
        if(index != -1){
            Component comp = ribbon.getComponent(index);
        
            //if component is avilable
            if(comp != null){
                JPanel panel = (JPanel)comp;
                Component[] comps = panel.getComponents();
                for(int i = 0; i < comps.length; i++){
                    Component btnComp = comps[i];
                    if(btnComp != null){
                        javax.swing.JButton btn = (javax.swing.JButton)btnComp;
                        if(btn.getText().equals(btnName)){
                            btn.setEnabled(enabled);
                        }
                    }
                }
            }
        }
    }

    @Override
    public void addToolKit(JPanel tb) {
        ribbon.addTab(tb.getName(), tb);
    }

    @Override
    public void addToDesktop(Component comp) {
        this.desktop.add(comp);
    }

}
